### ISSUE TITLE
Doesn't work on latest superagent(march 26, 2020)

### ISSUE THREAD

**Issue by shierro** [sebastianlzy/superagent-debugger#1]
Hi, i tried using the example and got
```
superdebug is not a function
```

**Comment by Enet4** [comment]
To those stumbling upon this issue, the latest version of the package exports the middleware function via `default`, possibly for compatibility with ECMAScript modules. The following works with superagent ^6.1.0.

```javascript
import superagentdebug from 'superagent-debugger';
```
or
```javascript
const superagentdebug = require('superagent-debugger').default;
```

**Comment by nohchi93** [comment]
I get the same error on the latest version when using ECMAScript module. Can't use CommonJs
